// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Job struct {
	ID          int64          `json:"id"`
	AbsoluteUrl string         `json:"absolute_url"`
	Data        interface{}    `json:"data"`
	Source      sql.NullString `json:"source"`
}

type SchemaMigration struct {
	Version string `json:"version"`
}
