// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Job struct {
	ID          int64
	AbsoluteUrl string
	Data        interface{}
}

type SchemaMigration struct {
	Version string
}
