// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const getJob = `-- name: GetJob :one
SELECT id, absolute_url, data FROM jobs
WHERE id = ? LIMIT 1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(&i.ID, &i.AbsoluteUrl, &i.Data)
	return i, err
}
