// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (absolute_url, data)
VALUES (?, ?)
RETURNING id, absolute_url, data, source
`

type CreateJobParams struct {
	AbsoluteUrl string      `json:"absolute_url"`
	Data        interface{} `json:"data"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob, arg.AbsoluteUrl, arg.Data)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.AbsoluteUrl,
		&i.Data,
		&i.Source,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, absolute_url, data, source FROM jobs
WHERE id = ? LIMIT 1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.AbsoluteUrl,
		&i.Data,
		&i.Source,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, absolute_url, data, source FROM jobs
ORDER BY id
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.AbsoluteUrl,
			&i.Data,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
