version: "2"
linters:
  default: all
  disable:
    - lll
    - gochecknoglobals
    - exhaustruct
    - wsl
    - nlreturn
  enable:
    - sloglint
  settings:
    sloglint:
      # Enforce using attributes only.
      # This will raise an error for any key-value pair arguments.
      attr-only: true